server:
  port: 8083
  servlet:
    context-path: /exchange/v1

spring:
  application:
    name: CurrencyExchangeService
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/exchange?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: exdevdb
    password: KQmK82dd
    hikari:
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1;
      connection-test-query: SELECT 2;
      minimum-idle: 5
      maximum-pool-size: 200
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: indexes/
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_update: true
        enable_lazy_load_no_trans: true
      show_sql: true
      format_sql: true
    open-in-view: false
  redis:
    host: 172.10.10.236
    port: 6379
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
  cloud:
    consul:
      port: 8500
      host: 172.50.10.5
      enabled: true
      discovery:
        enabled: true
        lifecycle:
          enabled: true
        heartbeat:
          enabled: true
          interval-ratio: 0.1
        health-check-timeout: 3s
        health-check-interval: 3ss
        tags: exchange-service
        service-name: exchange-service
        port: 8083
  flyway:
    enabled: false

logging:
  level:
    org:
      hibernate:
        type: debug

swagger:
  enabled: true

scheduled:
  update:
    currency: 0 */10 * ? * *

exchangers:
  coinlib:
    api-url:
      coin: https://coinlib.io/api/v1/coin
    api-key: 'a5c162aa66e69ee6'
    csv: coinlib.csv
  coinmarketcup:
    api-url:
      ticker: https://api.coinmarketcap.com/v1/ticker/
    csv: coinmarketcup.csv
  exrates:
    api-url:
      ticker: https://exrates.me/openapi/v1/public/ticker
  freecurrency:
    api-url:
      convert: https://free.currencyconverterapi.com/api/v6/convert
  worldcoinindex:
    api-url:
      ticker: https://www.worldcoinindex.com/apiservice/ticker
    api-key: 'GGJokOdeHrwab8hR8AdVDSn6k3kg4P'



